# config/routes.yaml
homepage:
  path: /home
  defaults: { _controller: 'App\Controller\DefaultController::index' }

login:
  path: /
  defaults: { _controller: 'App\Controller\SecurityController::login' }

contact:
  path: /contact
  defaults: { _controller: 'App\Controller\ContactController::contact' }

mock-form:
  path: /form
  defaults: { _controller: 'App\Controller\MockFormController::form' }

job:
  path: /job
  defaults: { _controller: 'App\Controller\JobController::create' }